#!/usr/bin/env bash

# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$SCRIPTDIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

CURDIR=`pwd`

while [ ! -e "$CURDIR/package.json" ]; do
    if [ "$CURDIR" == "/" ]; then
        echo "Cannot find package.json" >&2
        exit 1
    fi
    CURDIR=`cd $CURDIR/..; pwd`
done

SETENVCMD=`node $SCRIPTDIR/dependencyEnv.js $CURDIR`
# Use like this:
# $(dependencyEnv) && command
echo $SETENVCMD
