#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

export oldFishDir="$HOME/.config/fish/"

fishHitory="$oldFishDir/fish_history"

ln -fs $fishHitory $DIR/fish/fish_history

eval $($DIR/dependencyEnv)

export XDG_CONFIG_HOME=$DIR

fish