#!/usr/bin/env bash -i

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

export OLD_PS1="$PS1"

export OLD_PATH="$PATH"

export OLD_PROMPT="$PROMPT"

if [ -n "${ZSH_VERSION-}" ]; then
    export PS1="%{%F{red}%}[RE]%{%f%}$PS1"
else
    export PS1="\[\033[0;31m\][RE]\[\033[0m\]$PS1"
fi

deactivate () {
    PS1="$OLD_PS1"
    PATH="$OLD_PATH"
    PROMPT="$OLD_PROMPT"
}

eval $(dependencyEnv)
