#!/usr/bin/env bash -i

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

OLD_ZSHPROMPT=$(zsh -i $DIR/zshprompt)

export PROMPT="%{%F{red}%}[RE]%{%f%}$OLD_ZSHPROMPT"

eval $($DIR/dependencyEnv)

echo "$PROMPT"

zsh
